data_path: "../data/raw/data.csv"
model_path: "../models/logistic_regression_model.pkl"
transformer_path: "../models/transformer.pkl"
metric_path: "../models/metrics.json"
log_path: "../configs/logging_config.yaml"
splitting_params:
  val_size: 0.1
  random_state: 0
  stratify: False
model_type: "LogisticRegression"
feature_params:
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "fbs"
    - "thalach"
    - "oldpeak"
  categorical_features:
    - "sex"
    - "cp"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  target_col: "target"
gs_params:
  'param_grid':
    'C':
      - 100
      - 10
      - 1
      - 0.1
      - 0.01
      - 0.001
    'max_iter':
      - 10000
  'cv': 4
  'scoring': 'roc_auc'
